### ISSUE TITLE
Help in git workflow: how to safely push updates when "remote contains work that you do not have locally"

### ISSUE THREAD

**Issue by jtragtenberg** [probatio/probatio#13]
Since I'm new to git workflow, I don't know how to proceed. I'm afraid to mess up with the repo so I'm asking for help:

I didn't have the latest version of the probatio/probatio-3d-printing repository and I created and renamed some files in it. I can't push before updating it, but I don't know if by git pulling it I will lose anything I just did.
I got this error message: 

```
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/probatio/probatio-3dprinting.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

What should I do before pushing my commit?

**Comment by jtragtenberg** [comment]
I tried to do a "git pull" and I got this message. I believe some file changed by someone else I had also changed, probably a file name:
```
Merge branch 'master' of https://github.com/probatio/probatio-3dprinting
# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.
```
What should I do here?

**Comment by DocSunset** [comment]
There are probably many ways to deal with this. I think (if I understand the situation) what I would do is 

- `git checkout -b filenames`, then commit your local changes to the filenames branch. 
- Then you can `git checkout master` and `git pull` the remote changes, `git checkout filenames` to switch back to your feature branch, and `git merge master` to merge the remote changes into your feature branch. 
- Then you can either `git checkout master` and `git merge filenames` to merge your changes locally before `git push`ing changes upstream, 
- or you can `git checkout filenames`, `git push -u origin filenames' to push your local changes to a feature branch upstream, and then you can open a pull request on github and ask for a review before your changes get merged to master.

**Comment by DocSunset** [comment]
That might be a bit convoluted though...

**Comment by DocSunset** [comment]
You might be able to just commit your local changes, and then do `git pull`; it will complain that it can't automatically merge, and you will have to manually deal with the conflicts and `git commit` to finish the merge yourself?

**Comment by DocSunset** [comment]
The text box "`Merge branch 'master' of https://github.com/probatio/probatio-3dprinting`" in your second comment is just composing a commit message, specifically one for your merge from upstream. I think you can just save and quit your text editor and you'll be done a merge.

**Comment by DocSunset** [comment]
You address your original concern directly, 

>I don't know if by git pulling it I will lose anything I just did

As long as you had already run `git add` on your local changes, it's very difficult to lose them. If you already committed them, it's almost impossible to lose them without deliberately deleting things.

Your hard drive can of course fail suddenly, or other such unforeseen disasters, but you generally can't lose something that you have added or committed to git by running git commands, except if you're deliberately running a git command that is meant to delete things.

**Comment by jtragtenberg** [comment]
Great, thank you. That is what I wanted to know. I will try next time to create a new branch. So the second best workflow when this happens without using branches it to:
```
git add . 
git commit -m "..." 
git pull
git push

```
?

**Comment by jtragtenberg** [comment]
or should I always first do a "git pull" before anything?

**Comment by DocSunset** [comment]
I would say it’s always best to pull before you start making changes, but once you’ve made changes the commands you describe are exactly right, assuming you are working on a branch that is already set up with an upstream remote. 

```sh
git pull # in case someone else has made changes
# work locally
git add stuff
git commit -m ‘...’ # or just `git commit` 
                    # to compose a message with your $EDITOR
# go to # work locally
# until done working
git push
```

If push fails because someone else already made upstream changes:

```sh
git pull
# possibly manually complete the merge, 
# ending with `git commit` to finish the manual merge
git push
```

It would be the same if you were on a feature branch collaborating with someone as if you are directly pushing and pulling to the main branch.

**Comment by DocSunset** [comment]
Obviously if you’re working on your own local feature branch by yourself it would be a little bit different, e.g.

```sh
git checkout -b featurename 
# work locally
git add changed.file fileglob.* etc.txt
git commit -m ‘...’
# go to # work locally
# until done working and ready to push upstream
git push -u origin featurename
```
And then you can open a pull request on GitHub, and switch to the workflow as described for a branch with remote upstream if you need to collaborate with others to make it ready to merge.

**Comment by DocSunset** [comment]
Closing this issue for now. Please reopen if you have similar issues again; otherwise, for novel git/github challenges we can open a new issue.
